### PR TITLE
Added profile of Ganesh

### PR DESCRIPTION
**Pull request by SagareGanesh**

### CODE REVIEW

**Comment by Shwetakale** [comment]
@SagareGanesh Please upload photo with 150*150 size.

**Comment by SagareGanesh** [comment]
@Shwetakale  uploaded image with 150*150 size

**Comment by gautamrege** [comment]
Please update pull request. merge conflicts.

**Comment by SagareGanesh** [comment]
@gautamrege  ok

**Comment by SagareGanesh** [comment]
@gautamrege @Shwetakale  resolved conflicts.

**Pull request merged**
