### PR TITLE
Website in react with new UI

### PR DESCRIPTION
**Pull request by rdgadekar**
This PR includes new UI of In News pages.

### CODE REVIEW

**Review by sahilbhatia — CHANGES_REQUESTED** [review]
Please fix the compile time errors/warnings on browser console as well as terminal.

Screenshot from 2021-07-27 09-49-00

Screenshot from 2021-07-27 09-51-06

Screenshot from 2021-07-27 09-51-31

Screenshot from 2021-07-27 09-51-42

**Comment by sahilbhatia** [comment]
@swapnilchincholkar 

1. on `/media-coverage` route, we are getting `401` from `https://intranet.joshsoftware.com/api/v1/news`. Is it know to fail locally?
2. `/team` page is broken

**Comment by rdgadekar** [comment]
> Please fix the compile time errors/warnings on browser console as well as terminal.
> 
> Screenshot from 2021-07-27 09-49-00
> 
> Screenshot from 2021-07-27 09-51-06
> 
> Screenshot from 2021-07-27 09-51-31
> 
> Screenshot from 2021-07-27 09-51-42

Removed compile time errors/warnings.

**Review by sahilbhatia — CHANGES_REQUESTED** [review]
When visiting Talks section:
Screenshot from 2021-07-27 21-27-03

When visiting Publications section:
Screenshot from 2021-07-27 21-27-22

When visiting WhitePapers section:
Screenshot from 2021-07-27 21-27-47

**Comment by rdgadekar** [comment]
> When visiting Talks section:
> Screenshot from 2021-07-27 21-27-03
> 
> When visiting Publications section:
> Screenshot from 2021-07-27 21-27-22
> 
> When visiting WhitePapers section:
> Screenshot from 2021-07-27 21-27-47

Removed it from all the pages. My bad only checked landing page eariler.

**Review by sahilbhatia — DISMISSED** [review]

**Review by sahilbhatia — COMMENTED** [review]
We should consider using lazy loading as the news pages are getting quite heavy on page load.

**Review by sahilbhatia — APPROVED** [review]
We should consider using lazy loading as the news pages are getting quite heavy on page load.

**Pull request merged**
